---
apiVersion: v1
kind: Service
metadata:
  name: prod-eu-svc
  namespace: prod
spec:
  selector:
    app: trivial-go-web-app
  type: NodePort
  ports:
  - port: 9000
    nodePort: 31100
    protocol: TCP
    targetPort: 8080
