---
apiVersion: v1
kind: Service
metadata:
  name: qa-svc
  namespace: qa
spec:
  selector:
    app: trivial-go-web-app
  type: NodePort
  ports:
  - port: 9000
    nodePort: 31000
    protocol: TCP
    targetPort: 8080
