---
apiVersion: v1
kind: Service
metadata:
  name: staging-eu-svc
  namespace: staging
spec:
  selector:
    app: trivial-go-web-app
  type: NodePort
  ports:
  - port: 9000
    nodePort: 31200
    protocol: TCP
    targetPort: 8080
